name: .NET

on:
  push:
    # Solo se ejecuta si haces push a esta rama específica.
    branches: [ "feature/create-user-module" ] 
  
  pull_request:
    # Este evento se mantiene, ya que se encarga de ejecutar las pruebas 
    # cuando se abre un Pull Request hacia la rama 'master'.
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal